
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry nombre;
	private global::Gtk.Entry codigo;
	private global::Gtk.ComboBox grupo;
	private global::Gtk.Label Nombre;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.RadioButton opca;
	private global::Gtk.Label label7;
	private global::Gtk.RadioButton radiobutton2;
	private global::Gtk.Label label1;
	private global::Gtk.RadioButton radiobutton3;
	private global::Gtk.Label label8;
	private global::Gtk.RadioButton radiobutton4;
	private global::Gtk.Label label6;
	private global::Gtk.Label label9;
	private global::Gtk.Label label10;
	private global::Gtk.SpinButton spm;
	private global::Gtk.Label label11;
	private global::Gtk.Label label12;
	private global::Gtk.Label label13;
	private global::Gtk.CheckButton opa;
	private global::Gtk.Label label14;
	private global::Gtk.CheckButton checkbutton2;
	private global::Gtk.Label label15;
	private global::Gtk.CheckButton checkbutton3;
	private global::Gtk.Label label16;
	private global::Gtk.CheckButton opd;
	private global::Gtk.Label label17;
	private global::Gtk.Label label18;
	private global::Gtk.Calendar calendario;
	private global::Gtk.Button Terminar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.nombre = new global::Gtk.Entry ();
		this.nombre.CanFocus = true;
		this.nombre.Name = "nombre";
		this.nombre.IsEditable = true;
		this.nombre.InvisibleChar = '●';
		this.fixed1.Add (this.nombre);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.nombre]));
		w1.X = 112;
		w1.Y = 40;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.codigo = new global::Gtk.Entry ();
		this.codigo.CanFocus = true;
		this.codigo.Name = "codigo";
		this.codigo.IsEditable = true;
		this.codigo.InvisibleChar = '●';
		this.fixed1.Add (this.codigo);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.codigo]));
		w2.X = 112;
		w2.Y = 85;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.grupo = global::Gtk.ComboBox.NewText ();
		this.grupo.AppendText (global::Mono.Unix.Catalog.GetString ("A"));
		this.grupo.AppendText (global::Mono.Unix.Catalog.GetString ("B"));
		this.grupo.AppendText (global::Mono.Unix.Catalog.GetString ("C"));
		this.grupo.AppendText (global::Mono.Unix.Catalog.GetString ("D"));
		this.grupo.AppendText (global::Mono.Unix.Catalog.GetString ("E"));
		this.grupo.AppendText ("");
		this.grupo.Name = "grupo";
		this.fixed1.Add (this.grupo);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.grupo]));
		w3.X = 474;
		w3.Y = 52;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Nombre = new global::Gtk.Label ();
		this.Nombre.Name = "Nombre";
		this.Nombre.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
		this.fixed1.Add (this.Nombre);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Nombre]));
		w4.X = 52;
		w4.Y = 44;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Codigo");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w5.X = 55;
		w5.Y = 88;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Grupo");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w6.X = 420;
		w6.Y = 57;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("1.-");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w7.X = 49;
		w7.Y = 154;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("¿Cual numero se obtiene de multiplicar 2 a la 5 potencia?");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w8.X = 78;
		w8.Y = 154;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opca = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("32"));
		this.opca.CanFocus = true;
		this.opca.Name = "opca";
		this.opca.DrawIndicator = true;
		this.opca.UseUnderline = true;
		this.opca.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.opca);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opca]));
		w9.X = 75;
		w9.Y = 194;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("b)");
		this.fixed1.Add (this.label7);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
		w10.X = 131;
		w10.Y = 197;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("5"));
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = this.opca.Group;
		this.fixed1.Add (this.radiobutton2);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton2]));
		w11.X = 153;
		w11.Y = 195;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("c)");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w12.X = 206;
		w12.Y = 196;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton3 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("45"));
		this.radiobutton3.CanFocus = true;
		this.radiobutton3.Name = "radiobutton3";
		this.radiobutton3.DrawIndicator = true;
		this.radiobutton3.UseUnderline = true;
		this.radiobutton3.Group = this.opca.Group;
		this.fixed1.Add (this.radiobutton3);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton3]));
		w13.X = 229;
		w13.Y = 196;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("d)");
		this.fixed1.Add (this.label8);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
		w14.X = 287;
		w14.Y = 197;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton4 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("56"));
		this.radiobutton4.CanFocus = true;
		this.radiobutton4.Name = "radiobutton4";
		this.radiobutton4.DrawIndicator = true;
		this.radiobutton4.UseUnderline = true;
		this.radiobutton4.Group = this.opca.Group;
		this.fixed1.Add (this.radiobutton4);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton4]));
		w15.X = 312;
		w15.Y = 195;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("a)");
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w16.X = 52;
		w16.Y = 195;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("2.-");
		this.fixed1.Add (this.label9);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
		w17.X = 48;
		w17.Y = 245;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("¿ Cuanto es 2 + 2 ? ");
		this.fixed1.Add (this.label10);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label10]));
		w18.X = 80;
		w18.Y = 245;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spm = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.spm.CanFocus = true;
		this.spm.Name = "spm";
		this.spm.Adjustment.PageIncrement = 10D;
		this.spm.ClimbRate = 1D;
		this.spm.Numeric = true;
		this.fixed1.Add (this.spm);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spm]));
		w19.X = 77;
		w19.Y = 269;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("3.-");
		this.fixed1.Add (this.label11);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label11]));
		w20.X = 44;
		w20.Y = 320;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("¿ De los siguientes paises cuales son de America ?");
		this.fixed1.Add (this.label12);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label12]));
		w21.X = 75;
		w21.Y = 320;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("a)");
		this.fixed1.Add (this.label13);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label13]));
		w22.X = 68;
		w22.Y = 352;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opa = new global::Gtk.CheckButton ();
		this.opa.CanFocus = true;
		this.opa.Name = "opa";
		this.opa.Label = global::Mono.Unix.Catalog.GetString ("Mexico");
		this.opa.DrawIndicator = true;
		this.opa.UseUnderline = true;
		this.fixed1.Add (this.opa);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opa]));
		w23.X = 89;
		w23.Y = 352;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("b)");
		this.fixed1.Add (this.label14);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label14]));
		w24.X = 163;
		w24.Y = 354;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton2 = new global::Gtk.CheckButton ();
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString ("España");
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.fixed1.Add (this.checkbutton2);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton2]));
		w25.X = 186;
		w25.Y = 355;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("c)");
		this.fixed1.Add (this.label15);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label15]));
		w26.X = 262;
		w26.Y = 356;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton3 = new global::Gtk.CheckButton ();
		this.checkbutton3.CanFocus = true;
		this.checkbutton3.Name = "checkbutton3";
		this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString ("Japon");
		this.checkbutton3.DrawIndicator = true;
		this.checkbutton3.UseUnderline = true;
		this.fixed1.Add (this.checkbutton3);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton3]));
		w27.X = 284;
		w27.Y = 355;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("d)");
		this.fixed1.Add (this.label16);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label16]));
		w28.X = 355;
		w28.Y = 356;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opd = new global::Gtk.CheckButton ();
		this.opd.CanFocus = true;
		this.opd.Name = "opd";
		this.opd.Label = global::Mono.Unix.Catalog.GetString ("Peru");
		this.opd.DrawIndicator = true;
		this.opd.UseUnderline = true;
		this.fixed1.Add (this.opd);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opd]));
		w29.X = 374;
		w29.Y = 355;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("4.-");
		this.fixed1.Add (this.label17);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label17]));
		w30.X = 46;
		w30.Y = 414;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Indique la fecha de la independencia");
		this.fixed1.Add (this.label18);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label18]));
		w31.X = 84;
		w31.Y = 414;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendario = new global::Gtk.Calendar ();
		this.calendario.CanFocus = true;
		this.calendario.Name = "calendario";
		this.calendario.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calendario);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calendario]));
		w32.X = 94;
		w32.Y = 447;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Terminar = new global::Gtk.Button ();
		this.Terminar.CanFocus = true;
		this.Terminar.Name = "Terminar";
		this.Terminar.UseUnderline = true;
		this.Terminar.Label = global::Mono.Unix.Catalog.GetString ("Terminar");
		this.fixed1.Add (this.Terminar);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Terminar]));
		w33.X = 473;
		w33.Y = 648;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 756;
		this.DefaultHeight = 780;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Terminar.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
	}
}
